package tn.insat.redditkafka;

public class RedditComment {

    public String kind;
    public RedditCommentData data;

}


// {
//////        "kind": "t1",
//////        "data": {
//////          "subreddit_id": "t5_7hqomg",
//////          "approved_at_utc": null,
//////          "author_is_blocked": false,
//////          "comment_type": null,
//////          "link_title": "I have GPT-4 access as a free user now",
//////          "mod_reason_by": null,
//////          "banned_by": null,
//////          "ups": 1,
//////          "num_reports": null,
//////          "author_flair_type": "text",
//////          "total_awards_received": 0,
//////          "subreddit": "ChatGPT",
//////          "link_author": "Devfiend",
//////          "likes": null,
//////          "replies": "",
//////          "user_reports": [],
//////          "saved": false,
//////          "id": "jikdazj",
//////          "banned_at_utc": null,
//////          "mod_reason_title": null,
//////          "gilded": 0,
//////          "archived": false,
//////          "collapsed_reason_code": null,
//////          "no_follow": true,
//////          "author": "Ansunian",
//////          "num_comments": 369,
//////          "can_mod_post": false,
//////          "send_replies": true,
//////          "parent_id": "t3_134t0sc",
//////          "score": 1,
//////          "author_fullname": "t2_brnzcpor",
//////          "over_18": false,
//////          "report_reasons": null,
//////          "removal_reason": null,
//////          "approved_by": null,
//////          "controversiality": 0,
//////          "body": "They promised paid users early access to new features. What a joke.",
//////          "edited": false,
//////          "top_awarded_type": null,
//////          "downs": 0,
//////          "author_flair_css_class": null,
//////          "is_submitter": false,
//////          "collapsed": false,
//////          "author_flair_richtext": [],
//////          "author_patreon_flair": false,
//////          "body_html": "&lt;div class=\"md\"&gt;&lt;p&gt;They promised paid users early access to new features. What a joke.&lt;/p&gt;\n&lt;/div&gt;",
//////          "gildings": {},
//////          "collapsed_reason": null,
//////          "distinguished": null,
//////          "associated_award": null,
//////          "stickied": false,
//////          "author_premium": false,
//////          "can_gild": true,
//////          "link_id": "t3_134t0sc",
//////          "unrepliable_reason": null,
//////          "author_flair_text_color": null,
//////          "score_hidden": true,
//////          "permalink": "/r/ChatGPT/comments/134t0sc/i_have_gpt4_access_as_a_free_user_now/jikdazj/",
//////          "subreddit_type": "public",
//////          "link_permalink": "https://www.reddit.com/r/ChatGPT/comments/134t0sc/i_have_gpt4_access_as_a_free_user_now/",
//////          "name": "t1_jikdazj",
//////          "author_flair_template_id": null,
//////          "subreddit_name_prefixed": "r/ChatGPT",
//////          "author_flair_text": null,
//////          "treatment_tags": [],
//////          "created": 1683037038.0,
//////          "created_utc": 1683037038.0,
//////          "awarders": [],
//////          "all_awardings": [],
//////          "locked": false,
//////          "author_flair_background_color": null,
//////          "collapsed_because_crowd_control": null,
//////          "mod_reports": [],
//////          "quarantine": false,
//////          "mod_note": null,
//////          "link_url": "https://imgur.com/a/OQApTNJ"
//////        }
//////      }